# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				arrow = true
				donkey = true
				cow = true
				chest_minecart = true
				pig = true
				skeleton = true
				iron_golem = true
				bat = true
				frog = true
				area_effect_cloud = true
				rabbit = true
				cat = true
				zombie = true
				sheep = true
				player = true
				item = true
				villager = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				boat = true
				item_frame = true
				horse = true
				painting = true
				cave_spider = true
				glow_squid = true
				glow_item_frame = false
				spider = true
				creeper = true
				enderman = true

